### PR TITLE
v0.18.0

### PR DESCRIPTION
**Pull request by DeviateFish**
Early PR for 0.18.0 for organizational purposes.

Going to attempt to organize these TODOs in the order they should happen.
- [x] Pick an ES6 transpiler (babeljs vs traceur?)
- [x] #9 Rewrite in ES6
- [x] #10 Update jshint
- [x] #8 Library should be more flexible on how it's imported (common vs AMD vs etc etc)

Open to comments on the babeljs vs traceur thing.  I'm leaning towards traceur, since it seems a little cleaner to set up, but would require pulling in the runtime in the final build step.  Not necessarily an issue, but adds a piece of complexity.

Regarding #9: this should be a relatively easy transformation pass.  Plus, this gives me opportunity to address #7 at the same time.  I probably won't be using too many ES6 features; probably mostly just classes and modules.
#10 - This means setting up jshint as the first build step in the pipeline, rather than one of the later steps.  Each file should be linted separately, so errors in files can be more easily located and fixed.  Probably should also be more strict with the linting, while I'm at it.
#8 is somewhat optional, and may be addressed by my choice of transpiler (not sure about this).  If not, it's a relatively trivial change to `_intro.js` and `_outro.js`, to provide the UMD wrapper.

The final action item is more of a housekeeping thing, and this first commit already addresses some of it.

### CODE REVIEW

**Comment by DeviateFish** [comment]
Going with babeljs; specifically, browserify w/ babelify transform.

Follow-up regarding #9 -- It's easy, but boy is it a slog.

**Comment by evshiron** [comment]
I have used traceur when I was playing around with nodejs and have no idea about babeljs, and the ECMAScript 6 stuff is really cool and convenient. Although I don't think it necessary to do so, for the lack of native support from browsers, and the transformers might generate broken code, but it worths a try.

I have seen a lot of new issues here, and may I ask are these for refactoring only or do you have further plans for this project? I haven't used much of grunt, bower and jshint so I may keep my hands off until the work is done.

**Comment by DeviateFish** [comment]
I have further plans for the project.  There's lots of things that the renderer doesn't yet support, but I've been having trouble maintaining the existing project in its current setup.

So, I figured it was time for a heavy refactoring, so it's easier to maintain, before going ahead with additional features.

The build process should remain the same, though.  `grunt build` to lint, es5 transpile, and uglify, and `grunt serve` to spin up a local server for testing.

After refactoring, I'm going to try to port particle systems back over (again).

**Comment by evshiron** [comment]
That's cool. When the refactoring is done I will be back to see where I can help :)

**Comment by DeviateFish** [comment]
Should be done by the end of this weekend.  I'm about 90% done with the rewrite process (many find and replace!), and from there it's just a matter of hooking everything up and seeing if it works.

I'm looking at making some api changes in the future, as well, but I'm going to see if I can pull this off without needing to make them for this version.  Just means the root file is going to be a big pile of imports and just a single export of an object that matches the old API

**Comment by DeviateFish** [comment]
Oh, I also opened a lot of those issues to sort of lay things out for the features I want to add going forward from the refactoring.  Basically, just giving myself a list of things I want to do, in a place where I won't forget them.

Trying to be more organized!

**Pull request merged**
