### PR TITLE
Version 0.21.0

### PR DESCRIPTION
**Pull request by DeviateFish**
More iteration on the animation system, which touches many other things.
- [x] Hooking up a proper scene graph (#24)
- [x] Animation system that allows for multiple animations on the same drawable (#22)
- [x] Use promises for asset resolution (#23)
- [x] Add SBULA (and fix) and KeyCapsule (#27)

### CODE REVIEW

**Comment by DeviateFish** [comment]
How to pull before committing... :-1:

**Comment by evshiron** [comment]
Woot, it's a surprise that this project is still going :)

**Comment by DeviateFish** [comment]
Someday I'll finish this PR...

**Comment by DeviateFish** [comment]
Going to defer #21, #16 and #18 for until 0.23.0

**Pull request merged**
