### PR TITLE
Add demo(entity-viewer)

### PR DESCRIPTION
**Pull request by Milkker**
Add a demo for preview inventory.

### CODE REVIEW

**Comment by DeviateFish** [comment]
I'll have to pull this down and check it out, but I like the idea.

I do plan on deprecating `Entities` at some point in time (see: #29), but I'll figure out how to update this demo when that time comes.

**Comment by DeviateFish** [comment]
Took a look at this, it's really cool.

Here's a screenshot, for anyone else following along:

image

Simple, but effective.  I'll definitely be updating this whenever I actually end up deprecating Entities, and probably expand it to show all the various game objects, probably grouped by game category (world, inventory, etc).

**Comment by DeviateFish** [comment]
Thanks for this!

**Comment by Milkker** [comment]
It's nice to me too.
Your project help me very much.
I can render model easier with your project, even if I don't know how the webGL work.

**Pull request merged**
